### ISSUE TITLE
critical bug in promise module git, failed to log about changes made

### ISSUE THREAD

**Issue by craigcomstock** [cfengine/modules#48]
When using the git promise I see

```
CRITICAL: Bug in promise module - Failed to log about changes made by a repaired git promise with promiser '/home/craig/src/project' (/home/craig/.cfagent/inputs/services/autorun/project.cf:7)
```

This was a recent change in master so this module needs to be adjusted

```
$ cf-agent -V
CFEngine Core 3.21.0a.18a4291bf
CFEngine Enterprise 3.21.0a.dad704bd3
```

**Comment by craigcomstock** [comment]
Will log a ticket in JIRA instead. Might have something to do with promise locking.

**Comment by olehermanse** [comment]
> Will log a ticket in JIRA instead. Might have something to do with promise locking.

@craigcomstock please put a link to the JIRA ticket here.
